export const ACTIONS = {
  AUTH_REQUEST_HANDLE_CALLBACK: 'AUTH_REQUEST_HANDLE_CALLBACK',
  AUTH_CALLBACK_FAIL: 'AUTH_CALLBACK_FAIL',
  MESSAGE_SHOW: 'MESSAGE_SHOW',
  HISTORY_REPLACE: 'HISTORY_REPLACE',
  HISTORY_GO: 'HISTORY_GO',
};
