version: '3'
services:
  fpm:
    build: ../kadath
    ports:
      - 9000
    volumes:
      - ../kadath:/srv/kadath
      - ./integrate/kadath.env:/srv/kadath/.env
  nginx:
    depends_on: 
      - fpm
    image: nginx:1.13-alpine
    ports:
      - 80
    volumes:
     - ../ulthar/dist:/svr/ulthar
     - ../underworld/build:/svr/underworld
     - ./etc/nginx-server.conf:/etc/nginx/conf.d/default.conf
  redis:
    image: redis:3.2-alpine
    ports:
      - 6379
